### ISSUE TITLE
Make a Flask config

### ISSUE THREAD

**Issue by digiry** [digiry/reading-status-slackapp#1]
개발 단계별 Config를 만들자.
단, 중요한 정보는 instance config나 환경변수로 설정할 수 있게 한다.

**TODO**

- [ ] Config object for Flask app
- [ ] Instance config for secure variables
- [ ] Load environment variables for secure variables
